### ISSUE TITLE
CSV Dateiausgabe HHP fixen

### ISSUE THREAD

**Issue by DieMichii** [OpenAdministration/StuFis#167]
Aktuell wird bei der CSV Ausgabe die Zellen als Text formatiert (in Excel), die Summe noch als Summeme ausgeben und die Zellen in der Summe sind um ein zu weit nach oben gesetzt

**Comment by lukas-staab** [comment]
ich kann die verschobene formel in libreoffice nicht nachvollziehen. schau mal ob der fehler in excel immer noch ist...
